name: Generate boats result for Cap Martinique 2026
run-name: Boats result generation for Cap Martinique 2026
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  #schedule:
  #   - cron: "0 */1 * * *"
jobs:
  Download-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out prod-capmartinique-2026
        uses: actions/checkout@v4
        with:
          ref: prod-capmartinique-2026
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Download reports
        run: node ./download-reports.js
      - name: Generate result
        run: node ./generate-result.js
      - run: echo "CurrentDT=$(date +'%d/%m %H')" >> $GITHUB_ENV
      - name: Push reports & result to repository
        uses: EndBug/add-and-commit@v9
        with:
          add: boats.json tracks.json boats_result.json
          message: "Update ${{ env.CurrentDT }}h GMT"
